name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please provide details below to help diagnose the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: "The application crashed when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run: `result-companion analyze -o output.xml`
        2. Notice error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: macOS 14.2
        - Python: 3.11.5
        - Result Companion: 1.2.3
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log File
      description: |
        **Attach `result_companion.log`** from temp directory:
        - Linux/macOS: `/tmp/result_companion.log`
        - Windows: `%TEMP%\result_companion.log`
      placeholder: |
        Drag & drop file or paste JSON log entries:
        {"timestamp": "2025-12-02 19:40:34,553", "logger": "RC", "level": "ERROR", ...}
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
