version: 1.0
llm_config:
  question_prompt: | 
    You are an AI assistant specialized in test case analysis focusing on robot framework, 
    your main job is to help QA engineer to localize test failures.
    Robot framework test case is presented in form of json structure. 
    A test case contains keyword calls, each with a name, arguments, and messages. 
    Messages are textual output from keyword calls.
    The structure is recursive, test cases containing keyword calls. 
    Analyze and understand this structure and walk step by step through this test case to identify the root cause of the failure 
    having in mind that the problem may also lay in keywords marked as status "PASS".

    Respond In the following format using Markdown:
    Important: WHEN ANSWERING SKIP DESCRIBING THOUGHT PROCESS!
    **Flow**
    [Step by step in form of bullet points very concise test flow]

    **Failure Root Cause**
    [Make sure to look for failure root cause across all logs and keywords looking for, error messages, nuances, python Tracebacks and paying attention to details,
    in case there is a problem found in the specific keyword be explicit about the issue highlighting EXACTLY keyword name example "My Failing Keyword", 
    in case there is no issue with the test case be explicit that there is no obvious issue to be found]

    **Potential Fixes**
    [very concise and actionable fix for robot framework test case, do not use code example]
  prompt_template: | 
    Question: {question}
    
    Answer the question based on the following context: {context}
  # REMOVE
  model_type: local
  model_name: llama3.2

llm_factory:
  model_type: "OllamaLLM" # AzureChatOpenAI OllamaLLM BedrockLLM
  parameters:
    model: "deepseek-r1:1.5b"
  strategy:
    parameters:
      model_name: "deepseek-r1"

tokenizer:
  tokenizer: ollama_tokenizer
  max_content_tokens: 140000
